version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - 4533
    environment:
      ND_SCANINTERVAL: 15m
      ND_LOGLEVEL: info
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "./data/music:/music:ro"
    networks:
      - proxy-net
networks:
  proxy-net:
    driver: bridge
    name: nginx_proxy_network